version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Docker Login
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_LOGIN --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            docker build -t po92/test_repository:<< pipeline.git.revision >> .
            docker push po92/test_repository:<< pipeline.git.revision >>
            docker tag po92/test_repository:<< pipeline.git.revision >> po92/test_repository:latest
            docker push po92/test_repository:latest

workflows:
  simple_workflow:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test