version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  
  build-and-push:
    docker:
      - image: cimg/node:16.10
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          docker-username: DOCKERHUB_LOGIN
          docker-password: DOCKERHUB_PASSWORD
      - docker/build:
          image: wongshennan/test_repository
      - docker/push:
          image: wongshennan/test_repository
  
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
              heroku container:login
              heroku stack:set container -a shennan-su-devops
              heroku container:push web -a shennan-su-devops
              heroku container:release web -a shennan-su-devops

workflows:
  ci_workflow:
    jobs:
      - test:
          filters:
            branches:
              only: main

  full_ci_cd_workflow:
    jobs:
      - test:
          filters:
            branches:
              only: release
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: release
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: release