version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: po92/test_repository
      - docker/push:
          image: po92/test_repository
      
  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: | 
              heroku container:login
              heroku stack:set container -a shennan-su-devops
              heroku container:push web -a shennan-su-devops
              heroku container:release web -a shennan-su-devops

workflows:
  simple_workflow:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
      - deploy:
          requires:
            - publish